### PR TITLE
WIP add data_source_volterra_service_policy

### PR DESCRIPTION
**Pull request by cohenaj194**
ref: https://github.com/volterraedge/terraform-provider-volterra/issues/95

### CODE REVIEW

**Comment by cohenaj194** [comment]
I have this working locally I just need the test to pass: 

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.volterra_service_policy.foobar will be read during apply
  # (config refers to values not yet known)
 <= data "volterra_service_policy" "foobar"  {
      + id        = (known after apply)
      + name      = "foobar"
      + namespace = "shared"
    }

  # volterra_service_policy.foobar will be created
  + resource "volterra_service_policy" "foobar" {
      + algo               = "FIRST_MATCH"
      + allow_all_requests = true
      + any_server         = true
      + id                 = (known after apply)
      + name               = "foobar"
      + namespace          = "shared"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test = {
      + id        = (known after apply)
      + name      = "foobar"
      + namespace = "shared"
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

volterra_service_policy.foobar: Creating...
volterra_service_policy.foobar: Creation complete after 1s [id=35ede2bf-6c9f-4920-bceb-63570a964012]
data.volterra_service_policy.foobar: Reading...
data.volterra_service_policy.foobar: Read complete after 0s [id=35ede2bf-6c9f-4920-bceb-63570a964012]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test = {
  "id" = "35ede2bf-6c9f-4920-bceb-63570a964012"
  "name" = "foobar"
  "namespace" = "shared"
}
```

**Comment by cohenaj194** [comment]
I have this working and the tests are creating the service policy test resource, then successfully using the data resouce.  But I have no idea why it is saying the plan is not empty and then failing. 

https://github.com/volterraedge/terraform-provider-volterra/pull/98/checks#step:6:199

```
Error:     testing.go:654: Step 0 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        UPDATE: data.volterra_service_policy.aikuqbdhiz
          id:        "" => "<computed>"
          name:      "" => "aikuqbdhiz"
          namespace: "" => "shared"
        
        
        
        STATE:
        
        volterra_service_policy.aikuqbdhiz:
          ID = 293dc667-86e0-459c-9394-cb8442e51e37
          provider = provider.volterra
          algo = FIRST_MATCH
          allow_all_requests = true
          any_server = true
          deny_all_requests = false
          description = 
          disable = false
          name = aikuqbdhiz
          namespace = shared
rest RPC: ves.io.schema.service_policy.API.Delete , Status: OK        , The 'service_policy' 'aikuqbdhiz' in namespace 'shared' was successfully deleted.
```

**Comment by sanabby** [comment]
Alex, Can you please update this PR.

**Comment by cohenaj194** [comment]
@sanabby this MR can be closed out as we merged in the main change and this was another option that added a few tests.

**Pull request closed without merging**
